export enum DS_ENV {
  // Colors - Surface
  BASE_SURFACE = "BASE_SURFACE",
  BASE_SURFACE_DIM = "BASE_SURFACE_DIM",
  BASE_SURFACE_BRIGHT = "BASE_SURFACE_BRIGHT",
  BASE_SURFACE_CONTAINER_LOWEST = "BASE_SURFACE_CONTAINER_LOWEST",
  BASE_SURFACE_CONTAINER_LOW = "BASE_SURFACE_CONTAINER_LOW",
  BASE_SURFACE_CONTAINER = "BASE_SURFACE_CONTAINER",
  BASE_SURFACE_CONTAINER_HIGH = "BASE_SURFACE_CONTAINER_HIGH",
  BASE_SURFACE_CONTAINER_HIGHEST = "BASE_SURFACE_CONTAINER_HIGHEST",
  BASE_ON_SURFACE = "BASE_ON_SURFACE",
  BASE_ON_SURFACE_VARIANT = "BASE_ON_SURFACE_VARIANT",
  BASE_INVERSE_SURFACE = "BASE_INVERSE_SURFACE",
  BASE_INVERSE_ON_SURFACE = "BASE_INVERSE_ON_SURFACE",
  BASE_OUTLINE = "BASE_OUTLINE",
  BASE_OUTLINE_VARIANT = "BASE_OUTLINE_VARIANT",
  BASE_SURFACE_TINT = "BASE_SURFACE_TINT",
  BASE_SURFACE_VARIANT = "BASE_SURFACE_VARIANT",

  // Colors - Primary
  BASE_PRIMARY = "BASE_PRIMARY",
  BASE_ON_PRIMARY = "BASE_ON_PRIMARY",
  BASE_PRIMARY_CONTAINER = "BASE_PRIMARY_CONTAINER",
  BASE_ON_PRIMARY_CONTAINER = "BASE_ON_PRIMARY_CONTAINER",
  BASE_INVERSE_PRIMARY = "BASE_INVERSE_PRIMARY",
  BASE_PRIMARY_FIXED = "BASE_PRIMARY_FIXED",
  BASE_PRIMARY_FIXED_DIM = "BASE_PRIMARY_FIXED_DIM",
  BASE_ON_PRIMARY_FIXED = "BASE_ON_PRIMARY_FIXED",
  BASE_ON_PRIMARY_FIXED_VARIANT = "BASE_ON_PRIMARY_FIXED_VARIANT",

  // Colors - Secondary
  BASE_SECONDARY = "BASE_SECONDARY",
  BASE_ON_SECONDARY = "BASE_ON_SECONDARY",
  BASE_SECONDARY_CONTAINER = "BASE_SECONDARY_CONTAINER",
  BASE_ON_SECONDARY_CONTAINER = "BASE_ON_SECONDARY_CONTAINER",
  BASE_SECONDARY_FIXED = "BASE_SECONDARY_FIXED",
  BASE_SECONDARY_FIXED_DIM = "BASE_SECONDARY_FIXED_DIM",
  BASE_ON_SECONDARY_FIXED = "BASE_ON_SECONDARY_FIXED",
  BASE_ON_SECONDARY_FIXED_VARIANT = "BASE_ON_SECONDARY_FIXED_VARIANT",

  // Colors - Tertiary
  BASE_TERTIARY = "BASE_TERTIARY",
  BASE_ON_TERTIARY = "BASE_ON_TERTIARY",
  BASE_TERTIARY_CONTAINER = "BASE_TERTIARY_CONTAINER",
  BASE_ON_TERTIARY_CONTAINER = "BASE_ON_TERTIARY_CONTAINER",
  BASE_TERTIARY_FIXED = "BASE_TERTIARY_FIXED",
  BASE_TERTIARY_FIXED_DIM = "BASE_TERTIARY_FIXED_DIM",
  BASE_ON_TERTIARY_FIXED = "BASE_ON_TERTIARY_FIXED",
  BASE_ON_TERTIARY_FIXED_VARIANT = "BASE_ON_TERTIARY_FIXED_VARIANT",

  // Colors - Status
  BASE_ERROR = "BASE_ERROR",
  BASE_ON_ERROR = "BASE_ON_ERROR",
  BASE_ERROR_CONTAINER = "BASE_ERROR_CONTAINER",
  BASE_ON_ERROR_CONTAINER = "BASE_ON_ERROR_CONTAINER",
  BASE_SUCCESS = "BASE_SUCCESS",
  BASE_SUCCESS_MUTED = "BASE_SUCCESS_MUTED",
  BASE_ALERT = "BASE_ALERT",
  BASE_ALERT_MUTED = "BASE_ALERT_MUTED",
  BASE_INFO = "BASE_INFO",
  BASE_INFO_MUTED = "BASE_INFO_MUTED",

  // Colors - Other
  BASE_BACKGROUND = "BASE_BACKGROUND",
  BASE_ON_BACKGROUND = "BASE_ON_BACKGROUND",

  // Typography - display-lg
  BASE_TYPOGRAPHY_DISPLAY_LG_SIZE = "BASE_TYPOGRAPHY_DISPLAY_LG_SIZE",
  BASE_TYPOGRAPHY_DISPLAY_LG_WEIGHT = "BASE_TYPOGRAPHY_DISPLAY_LG_WEIGHT",
  BASE_TYPOGRAPHY_DISPLAY_LG_LINEHEIGHT = "BASE_TYPOGRAPHY_DISPLAY_LG_LINEHEIGHT",
  BASE_TYPOGRAPHY_DISPLAY_LG_LETTERSPACING = "BASE_TYPOGRAPHY_DISPLAY_LG_LETTERSPACING",

  // Typography - headline-md
  BASE_TYPOGRAPHY_HEADLINE_MD_SIZE = "BASE_TYPOGRAPHY_HEADLINE_MD_SIZE",
  BASE_TYPOGRAPHY_HEADLINE_MD_WEIGHT = "BASE_TYPOGRAPHY_HEADLINE_MD_WEIGHT",
  BASE_TYPOGRAPHY_HEADLINE_MD_LINEHEIGHT = "BASE_TYPOGRAPHY_HEADLINE_MD_LINEHEIGHT",

  // Typography - title-sm
  BASE_TYPOGRAPHY_TITLE_SM_SIZE = "BASE_TYPOGRAPHY_TITLE_SM_SIZE",
  BASE_TYPOGRAPHY_TITLE_SM_WEIGHT = "BASE_TYPOGRAPHY_TITLE_SM_WEIGHT",
  BASE_TYPOGRAPHY_TITLE_SM_LINEHEIGHT = "BASE_TYPOGRAPHY_TITLE_SM_LINEHEIGHT",
  BASE_TYPOGRAPHY_TITLE_SM_LETTERSPACING = "BASE_TYPOGRAPHY_TITLE_SM_LETTERSPACING",

  // Typography - body-main
  BASE_TYPOGRAPHY_BODY_MAIN_SIZE = "BASE_TYPOGRAPHY_BODY_MAIN_SIZE",
  BASE_TYPOGRAPHY_BODY_MAIN_WEIGHT = "BASE_TYPOGRAPHY_BODY_MAIN_WEIGHT",
  BASE_TYPOGRAPHY_BODY_MAIN_LINEHEIGHT = "BASE_TYPOGRAPHY_BODY_MAIN_LINEHEIGHT",

  // Typography - data-mono
  BASE_TYPOGRAPHY_DATA_MONO_SIZE = "BASE_TYPOGRAPHY_DATA_MONO_SIZE",
  BASE_TYPOGRAPHY_DATA_MONO_WEIGHT = "BASE_TYPOGRAPHY_DATA_MONO_WEIGHT",
  BASE_TYPOGRAPHY_DATA_MONO_LINEHEIGHT = "BASE_TYPOGRAPHY_DATA_MONO_LINEHEIGHT",
  BASE_TYPOGRAPHY_DATA_MONO_LETTERSPACING = "BASE_TYPOGRAPHY_DATA_MONO_LETTERSPACING",

  // Typography - label-caps
  BASE_TYPOGRAPHY_LABEL_CAPS_SIZE = "BASE_TYPOGRAPHY_LABEL_CAPS_SIZE",
  BASE_TYPOGRAPHY_LABEL_CAPS_WEIGHT = "BASE_TYPOGRAPHY_LABEL_CAPS_WEIGHT",
  BASE_TYPOGRAPHY_LABEL_CAPS_LINEHEIGHT = "BASE_TYPOGRAPHY_LABEL_CAPS_LINEHEIGHT",

  // Rounded
  BASE_ROUNDED_SM = "BASE_ROUNDED_SM",
  BASE_ROUNDED_DEFAULT = "BASE_ROUNDED_DEFAULT",
  BASE_ROUNDED_MD = "BASE_ROUNDED_MD",
  BASE_ROUNDED_LG = "BASE_ROUNDED_LG",
  BASE_ROUNDED_XL = "BASE_ROUNDED_XL",
  BASE_ROUNDED_FULL = "BASE_ROUNDED_FULL",

  // Spacing
  BASE_SPACING_BASE = "BASE_SPACING_BASE",
  BASE_SPACING_XS = "BASE_SPACING_XS",
  BASE_SPACING_SM = "BASE_SPACING_SM",
  BASE_SPACING_MD = "BASE_SPACING_MD",
  BASE_SPACING_LG = "BASE_SPACING_LG",
  BASE_SPACING_XL = "BASE_SPACING_XL",
  BASE_SPACING_CONTAINER_MAX = "BASE_SPACING_CONTAINER_MAX",
  BASE_SPACING_GUTTER = "BASE_SPACING_GUTTER",
}

export enum WEB_ENV {
  API_BASE_URL = "API_BASE_URL",
}

export enum API_ENV {}
// Add api-specific environment variables here

export enum STORYBOOK_ENV {}
// Add storybook-specific environment variables here
