import { DS_ENV, WEB_ENV } from "./getEnv.types";

/**
 * Static Map for Environment Variables.
 *
 * IMPORTANT: We MUST use literal process.env.KEY names here.
 * Dynamic access (e.g., process.env[key]) fails in Next.js client-side
 * because the bundler needs to see the literal name to include it in the bundle.
 */
const ENV_MAP: Record<string, string | undefined> = {
  // Surface
  [DS_ENV.BASE_SURFACE]:
    process.env.BASE_SURFACE || process.env.NEXT_PUBLIC_BASE_SURFACE,
  [DS_ENV.BASE_SURFACE_DIM]:
    process.env.BASE_SURFACE_DIM || process.env.NEXT_PUBLIC_BASE_SURFACE_DIM,
  [DS_ENV.BASE_SURFACE_BRIGHT]:
    process.env.BASE_SURFACE_BRIGHT ||
    process.env.NEXT_PUBLIC_BASE_SURFACE_BRIGHT,
  [DS_ENV.BASE_SURFACE_CONTAINER_LOWEST]:
    process.env.BASE_SURFACE_CONTAINER_LOWEST ||
    process.env.NEXT_PUBLIC_BASE_SURFACE_CONTAINER_LOWEST,
  [DS_ENV.BASE_SURFACE_CONTAINER_LOW]:
    process.env.BASE_SURFACE_CONTAINER_LOW ||
    process.env.NEXT_PUBLIC_BASE_SURFACE_CONTAINER_LOW,
  [DS_ENV.BASE_SURFACE_CONTAINER]:
    process.env.BASE_SURFACE_CONTAINER ||
    process.env.NEXT_PUBLIC_BASE_SURFACE_CONTAINER,
  [DS_ENV.BASE_SURFACE_CONTAINER_HIGH]:
    process.env.BASE_SURFACE_CONTAINER_HIGH ||
    process.env.NEXT_PUBLIC_BASE_SURFACE_CONTAINER_HIGH,
  [DS_ENV.BASE_SURFACE_CONTAINER_HIGHEST]:
    process.env.BASE_SURFACE_CONTAINER_HIGHEST ||
    process.env.NEXT_PUBLIC_BASE_SURFACE_CONTAINER_HIGHEST,
  [DS_ENV.BASE_ON_SURFACE]:
    process.env.BASE_ON_SURFACE || process.env.NEXT_PUBLIC_BASE_ON_SURFACE,
  [DS_ENV.BASE_ON_SURFACE_VARIANT]:
    process.env.BASE_ON_SURFACE_VARIANT ||
    process.env.NEXT_PUBLIC_BASE_ON_SURFACE_VARIANT,
  [DS_ENV.BASE_INVERSE_SURFACE]:
    process.env.BASE_INVERSE_SURFACE ||
    process.env.NEXT_PUBLIC_BASE_INVERSE_SURFACE,
  [DS_ENV.BASE_INVERSE_ON_SURFACE]:
    process.env.BASE_INVERSE_ON_SURFACE ||
    process.env.NEXT_PUBLIC_BASE_INVERSE_ON_SURFACE,
  [DS_ENV.BASE_OUTLINE]:
    process.env.BASE_OUTLINE || process.env.NEXT_PUBLIC_BASE_OUTLINE,
  [DS_ENV.BASE_OUTLINE_VARIANT]:
    process.env.BASE_OUTLINE_VARIANT ||
    process.env.NEXT_PUBLIC_BASE_OUTLINE_VARIANT,
  [DS_ENV.BASE_SURFACE_TINT]:
    process.env.BASE_SURFACE_TINT || process.env.NEXT_PUBLIC_BASE_SURFACE_TINT,
  [DS_ENV.BASE_SURFACE_VARIANT]:
    process.env.BASE_SURFACE_VARIANT ||
    process.env.NEXT_PUBLIC_BASE_SURFACE_VARIANT,

  // Primary
  [DS_ENV.BASE_PRIMARY]:
    process.env.BASE_PRIMARY || process.env.NEXT_PUBLIC_BASE_PRIMARY,
  [DS_ENV.BASE_ON_PRIMARY]:
    process.env.BASE_ON_PRIMARY || process.env.NEXT_PUBLIC_BASE_ON_PRIMARY,
  [DS_ENV.BASE_PRIMARY_CONTAINER]:
    process.env.BASE_PRIMARY_CONTAINER ||
    process.env.NEXT_PUBLIC_BASE_PRIMARY_CONTAINER,
  [DS_ENV.BASE_ON_PRIMARY_CONTAINER]:
    process.env.BASE_ON_PRIMARY_CONTAINER ||
    process.env.NEXT_PUBLIC_BASE_ON_PRIMARY_CONTAINER,
  [DS_ENV.BASE_INVERSE_PRIMARY]:
    process.env.BASE_INVERSE_PRIMARY ||
    process.env.NEXT_PUBLIC_BASE_INVERSE_PRIMARY,
  [DS_ENV.BASE_PRIMARY_FIXED]:
    process.env.BASE_PRIMARY_FIXED ||
    process.env.NEXT_PUBLIC_BASE_PRIMARY_FIXED,
  [DS_ENV.BASE_PRIMARY_FIXED_DIM]:
    process.env.BASE_PRIMARY_FIXED_DIM ||
    process.env.NEXT_PUBLIC_BASE_PRIMARY_FIXED_DIM,
  [DS_ENV.BASE_ON_PRIMARY_FIXED]:
    process.env.BASE_ON_PRIMARY_FIXED ||
    process.env.NEXT_PUBLIC_BASE_ON_PRIMARY_FIXED,
  [DS_ENV.BASE_ON_PRIMARY_FIXED_VARIANT]:
    process.env.BASE_ON_PRIMARY_FIXED_VARIANT ||
    process.env.NEXT_PUBLIC_BASE_ON_PRIMARY_FIXED_VARIANT,

  // Secondary
  [DS_ENV.BASE_SECONDARY]:
    process.env.BASE_SECONDARY || process.env.NEXT_PUBLIC_BASE_SECONDARY,
  [DS_ENV.BASE_ON_SECONDARY]:
    process.env.BASE_ON_SECONDARY || process.env.NEXT_PUBLIC_BASE_ON_SECONDARY,
  [DS_ENV.BASE_SECONDARY_CONTAINER]:
    process.env.BASE_SECONDARY_CONTAINER ||
    process.env.NEXT_PUBLIC_BASE_SECONDARY_CONTAINER,
  [DS_ENV.BASE_ON_SECONDARY_CONTAINER]:
    process.env.BASE_ON_SECONDARY_CONTAINER ||
    process.env.NEXT_PUBLIC_BASE_ON_SECONDARY_CONTAINER,
  [DS_ENV.BASE_SECONDARY_FIXED]:
    process.env.BASE_SECONDARY_FIXED ||
    process.env.NEXT_PUBLIC_BASE_SECONDARY_FIXED,
  [DS_ENV.BASE_SECONDARY_FIXED_DIM]:
    process.env.BASE_SECONDARY_FIXED_DIM ||
    process.env.NEXT_PUBLIC_BASE_SECONDARY_FIXED_DIM,
  [DS_ENV.BASE_ON_SECONDARY_FIXED]:
    process.env.BASE_ON_SECONDARY_FIXED ||
    process.env.NEXT_PUBLIC_BASE_ON_SECONDARY_FIXED,
  [DS_ENV.BASE_ON_SECONDARY_FIXED_VARIANT]:
    process.env.BASE_ON_SECONDARY_FIXED_VARIANT ||
    process.env.NEXT_PUBLIC_BASE_ON_SECONDARY_FIXED_VARIANT,

  // Tertiary
  [DS_ENV.BASE_TERTIARY]:
    process.env.BASE_TERTIARY || process.env.NEXT_PUBLIC_BASE_TERTIARY,
  [DS_ENV.BASE_ON_TERTIARY]:
    process.env.BASE_ON_TERTIARY || process.env.NEXT_PUBLIC_BASE_ON_TERTIARY,
  [DS_ENV.BASE_TERTIARY_CONTAINER]:
    process.env.BASE_TERTIARY_CONTAINER ||
    process.env.NEXT_PUBLIC_BASE_TERTIARY_CONTAINER,
  [DS_ENV.BASE_ON_TERTIARY_CONTAINER]:
    process.env.BASE_ON_TERTIARY_CONTAINER ||
    process.env.NEXT_PUBLIC_BASE_ON_TERTIARY_CONTAINER,
  [DS_ENV.BASE_TERTIARY_FIXED]:
    process.env.BASE_TERTIARY_FIXED ||
    process.env.NEXT_PUBLIC_BASE_TERTIARY_FIXED,
  [DS_ENV.BASE_TERTIARY_FIXED_DIM]:
    process.env.BASE_TERTIARY_FIXED_DIM ||
    process.env.NEXT_PUBLIC_BASE_TERTIARY_FIXED_DIM,
  [DS_ENV.BASE_ON_TERTIARY_FIXED]:
    process.env.BASE_ON_TERTIARY_FIXED ||
    process.env.NEXT_PUBLIC_BASE_ON_TERTIARY_FIXED,
  [DS_ENV.BASE_ON_TERTIARY_FIXED_VARIANT]:
    process.env.BASE_ON_TERTIARY_FIXED_VARIANT ||
    process.env.NEXT_PUBLIC_BASE_ON_TERTIARY_FIXED_VARIANT,

  // Error
  [DS_ENV.BASE_ERROR]:
    process.env.BASE_ERROR || process.env.NEXT_PUBLIC_BASE_ERROR,
  [DS_ENV.BASE_ON_ERROR]:
    process.env.BASE_ON_ERROR || process.env.NEXT_PUBLIC_BASE_ON_ERROR,
  [DS_ENV.BASE_ERROR_CONTAINER]:
    process.env.BASE_ERROR_CONTAINER ||
    process.env.NEXT_PUBLIC_BASE_ERROR_CONTAINER,
  [DS_ENV.BASE_ON_ERROR_CONTAINER]:
    process.env.BASE_ON_ERROR_CONTAINER ||
    process.env.NEXT_PUBLIC_BASE_ON_ERROR_CONTAINER,

  // Success / Alert / Info
  [DS_ENV.BASE_SUCCESS]:
    process.env.BASE_SUCCESS || process.env.NEXT_PUBLIC_BASE_SUCCESS,
  [DS_ENV.BASE_SUCCESS_MUTED]:
    process.env.BASE_SUCCESS_MUTED ||
    process.env.NEXT_PUBLIC_BASE_SUCCESS_MUTED,
  [DS_ENV.BASE_ALERT]:
    process.env.BASE_ALERT || process.env.NEXT_PUBLIC_BASE_ALERT,
  [DS_ENV.BASE_ALERT_MUTED]:
    process.env.BASE_ALERT_MUTED || process.env.NEXT_PUBLIC_BASE_ALERT_MUTED,
  [DS_ENV.BASE_INFO]:
    process.env.BASE_INFO || process.env.NEXT_PUBLIC_BASE_INFO,
  [DS_ENV.BASE_INFO_MUTED]:
    process.env.BASE_INFO_MUTED || process.env.NEXT_PUBLIC_BASE_INFO_MUTED,

  // Typography - display-lg
  [DS_ENV.BASE_TYPOGRAPHY_DISPLAY_LG_SIZE]:
    process.env.BASE_TYPOGRAPHY_DISPLAY_LG_SIZE ||
    process.env.NEXT_PUBLIC_BASE_TYPOGRAPHY_DISPLAY_LG_SIZE,
  [DS_ENV.BASE_TYPOGRAPHY_DISPLAY_LG_WEIGHT]:
    process.env.BASE_TYPOGRAPHY_DISPLAY_LG_WEIGHT ||
    process.env.NEXT_PUBLIC_BASE_TYPOGRAPHY_DISPLAY_LG_WEIGHT,
  [DS_ENV.BASE_TYPOGRAPHY_DISPLAY_LG_LINEHEIGHT]:
    process.env.BASE_TYPOGRAPHY_DISPLAY_LG_LINEHEIGHT ||
    process.env.NEXT_PUBLIC_BASE_TYPOGRAPHY_DISPLAY_LG_LINEHEIGHT,
  [DS_ENV.BASE_TYPOGRAPHY_DISPLAY_LG_LETTERSPACING]:
    process.env.BASE_TYPOGRAPHY_DISPLAY_LG_LETTERSPACING ||
    process.env.NEXT_PUBLIC_BASE_TYPOGRAPHY_DISPLAY_LG_LETTERSPACING,

  // Typography - headline-md
  [DS_ENV.BASE_TYPOGRAPHY_HEADLINE_MD_SIZE]:
    process.env.BASE_TYPOGRAPHY_HEADLINE_MD_SIZE ||
    process.env.NEXT_PUBLIC_BASE_TYPOGRAPHY_HEADLINE_MD_SIZE,
  [DS_ENV.BASE_TYPOGRAPHY_HEADLINE_MD_WEIGHT]:
    process.env.BASE_TYPOGRAPHY_HEADLINE_MD_WEIGHT ||
    process.env.NEXT_PUBLIC_BASE_TYPOGRAPHY_HEADLINE_MD_WEIGHT,
  [DS_ENV.BASE_TYPOGRAPHY_HEADLINE_MD_LINEHEIGHT]:
    process.env.BASE_TYPOGRAPHY_HEADLINE_MD_LINEHEIGHT ||
    process.env.NEXT_PUBLIC_BASE_TYPOGRAPHY_HEADLINE_MD_LINEHEIGHT,

  // Typography - title-sm
  [DS_ENV.BASE_TYPOGRAPHY_TITLE_SM_SIZE]:
    process.env.BASE_TYPOGRAPHY_TITLE_SM_SIZE ||
    process.env.NEXT_PUBLIC_BASE_TYPOGRAPHY_TITLE_SM_SIZE,
  [DS_ENV.BASE_TYPOGRAPHY_TITLE_SM_WEIGHT]:
    process.env.BASE_TYPOGRAPHY_TITLE_SM_WEIGHT ||
    process.env.NEXT_PUBLIC_BASE_TYPOGRAPHY_TITLE_SM_WEIGHT,
  [DS_ENV.BASE_TYPOGRAPHY_TITLE_SM_LINEHEIGHT]:
    process.env.BASE_TYPOGRAPHY_TITLE_SM_LINEHEIGHT ||
    process.env.NEXT_PUBLIC_BASE_TYPOGRAPHY_TITLE_SM_LINEHEIGHT,
  [DS_ENV.BASE_TYPOGRAPHY_TITLE_SM_LETTERSPACING]:
    process.env.BASE_TYPOGRAPHY_TITLE_SM_LETTERSPACING ||
    process.env.NEXT_PUBLIC_BASE_TYPOGRAPHY_TITLE_SM_LETTERSPACING,

  // Typography - body-main
  [DS_ENV.BASE_TYPOGRAPHY_BODY_MAIN_SIZE]:
    process.env.BASE_TYPOGRAPHY_BODY_MAIN_SIZE ||
    process.env.NEXT_PUBLIC_BASE_TYPOGRAPHY_BODY_MAIN_SIZE,
  [DS_ENV.BASE_TYPOGRAPHY_BODY_MAIN_WEIGHT]:
    process.env.BASE_TYPOGRAPHY_BODY_MAIN_WEIGHT ||
    process.env.NEXT_PUBLIC_BASE_TYPOGRAPHY_BODY_MAIN_WEIGHT,
  [DS_ENV.BASE_TYPOGRAPHY_BODY_MAIN_LINEHEIGHT]:
    process.env.BASE_TYPOGRAPHY_BODY_MAIN_LINEHEIGHT ||
    process.env.NEXT_PUBLIC_BASE_TYPOGRAPHY_BODY_MAIN_LINEHEIGHT,

  // Typography - data-mono
  [DS_ENV.BASE_TYPOGRAPHY_DATA_MONO_SIZE]:
    process.env.BASE_TYPOGRAPHY_DATA_MONO_SIZE ||
    process.env.NEXT_PUBLIC_BASE_TYPOGRAPHY_DATA_MONO_SIZE,
  [DS_ENV.BASE_TYPOGRAPHY_DATA_MONO_WEIGHT]:
    process.env.BASE_TYPOGRAPHY_DATA_MONO_WEIGHT ||
    process.env.NEXT_PUBLIC_BASE_TYPOGRAPHY_DATA_MONO_WEIGHT,
  [DS_ENV.BASE_TYPOGRAPHY_DATA_MONO_LINEHEIGHT]:
    process.env.BASE_TYPOGRAPHY_DATA_MONO_LINEHEIGHT ||
    process.env.NEXT_PUBLIC_BASE_TYPOGRAPHY_DATA_MONO_LINEHEIGHT,
  [DS_ENV.BASE_TYPOGRAPHY_DATA_MONO_LETTERSPACING]:
    process.env.BASE_TYPOGRAPHY_DATA_MONO_LETTERSPACING ||
    process.env.NEXT_PUBLIC_BASE_TYPOGRAPHY_DATA_MONO_LETTERSPACING,

  // Typography - label-caps
  [DS_ENV.BASE_TYPOGRAPHY_LABEL_CAPS_SIZE]:
    process.env.BASE_TYPOGRAPHY_LABEL_CAPS_SIZE ||
    process.env.NEXT_PUBLIC_BASE_TYPOGRAPHY_LABEL_CAPS_SIZE,
  [DS_ENV.BASE_TYPOGRAPHY_LABEL_CAPS_WEIGHT]:
    process.env.BASE_TYPOGRAPHY_LABEL_CAPS_WEIGHT ||
    process.env.NEXT_PUBLIC_BASE_TYPOGRAPHY_LABEL_CAPS_WEIGHT,
  [DS_ENV.BASE_TYPOGRAPHY_LABEL_CAPS_LINEHEIGHT]:
    process.env.BASE_TYPOGRAPHY_LABEL_CAPS_LINEHEIGHT ||
    process.env.NEXT_PUBLIC_BASE_TYPOGRAPHY_LABEL_CAPS_LINEHEIGHT,

  // Rounded
  [DS_ENV.BASE_ROUNDED_SM]:
    process.env.BASE_ROUNDED_SM || process.env.NEXT_PUBLIC_BASE_ROUNDED_SM,
  [DS_ENV.BASE_ROUNDED_DEFAULT]:
    process.env.BASE_ROUNDED_DEFAULT ||
    process.env.NEXT_PUBLIC_BASE_ROUNDED_DEFAULT,
  [DS_ENV.BASE_ROUNDED_MD]:
    process.env.BASE_ROUNDED_MD || process.env.NEXT_PUBLIC_BASE_ROUNDED_MD,
  [DS_ENV.BASE_ROUNDED_LG]:
    process.env.BASE_ROUNDED_LG || process.env.NEXT_PUBLIC_BASE_ROUNDED_LG,
  [DS_ENV.BASE_ROUNDED_XL]:
    process.env.BASE_ROUNDED_XL || process.env.NEXT_PUBLIC_BASE_ROUNDED_XL,
  [DS_ENV.BASE_ROUNDED_FULL]:
    process.env.BASE_ROUNDED_FULL || process.env.NEXT_PUBLIC_BASE_ROUNDED_FULL,

  // Spacing
  [DS_ENV.BASE_SPACING_BASE]:
    process.env.BASE_SPACING_BASE || process.env.NEXT_PUBLIC_BASE_SPACING_BASE,
  [DS_ENV.BASE_SPACING_XS]:
    process.env.BASE_SPACING_XS || process.env.NEXT_PUBLIC_BASE_SPACING_XS,
  [DS_ENV.BASE_SPACING_SM]:
    process.env.BASE_SPACING_SM || process.env.NEXT_PUBLIC_BASE_SPACING_SM,
  [DS_ENV.BASE_SPACING_MD]:
    process.env.BASE_SPACING_MD || process.env.NEXT_PUBLIC_BASE_SPACING_MD,
  [DS_ENV.BASE_SPACING_LG]:
    process.env.BASE_SPACING_LG || process.env.NEXT_PUBLIC_BASE_SPACING_LG,
  [DS_ENV.BASE_SPACING_XL]:
    process.env.BASE_SPACING_XL || process.env.NEXT_PUBLIC_BASE_SPACING_XL,
  [DS_ENV.BASE_SPACING_CONTAINER_MAX]:
    process.env.BASE_SPACING_CONTAINER_MAX ||
    process.env.NEXT_PUBLIC_BASE_SPACING_CONTAINER_MAX,
  [DS_ENV.BASE_SPACING_GUTTER]:
    process.env.BASE_SPACING_GUTTER ||
    process.env.NEXT_PUBLIC_BASE_SPACING_GUTTER,

  // Web
  [WEB_ENV.API_BASE_URL]:
    process.env.API_BASE_URL || process.env.NEXT_PUBLIC_API_BASE_URL,
};

export function getEnv(key: string, fallback: string = ""): string {
  return ENV_MAP[key] || fallback;
}
